sudo: required
dist: trusty
language: python
python: "2.7"

services:
 - docker

env:
  global:
    - PATH="/usr/bin:$PATH"
    
before_install:
- deactivate
- sudo apt-get update -qq
- sudo apt-get install -y -o Dpkg::Options::="--force-confnew" docker-engine
- docker pull chrismeyers/centos6
- docker run -dt --name dingdock --expose 8080  chrismeyers/centos6
   
install:
- sudo pip install docker-py
- sudo apt-add-repository -y ppa:ansible/ansible
- sudo apt-get update -qq
- sudo apt-get install -y ansible
- sudo rm /usr/bin/python && sudo ln -s /usr/bin/python2.7 /usr/bin/python
- ansible --version
- ansible-galaxy install -r test/requirements.yml -p test/roles/
script:
- sudo ansible all -i "127.0.0.1," -m lineinfile -a "regexp=^#host_key_checking dest=/etc/ansible/ansible.cfg line='host_key_checking = False'" -c local
- ansible -m ping all -i tests/inventory
- ansible-playbook -i tests/inventory tests/main.yml 
