sudo: required
language: python
python: "2.7"

services:
 - docker

before_install:
- docker pull centos6
- docker run -dt --name dingdock --expose 8080  centos6
   
install:
- pip install ansible

script:
- ansible-playbook -i test/inventory tests/test.yml --syntax-check
