#!/bin/bash
#
# /etc/init.d/dingrod
#
# chkconfig: 2345 95 05
# description: dingrod service daemon
#
# processname: dingrod

start()
{
}

stop()
{
}




case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    stop
    start
    ;;
  status)
    status $prog
    RETVAL=$?
    ;;
  *)
    echo $"USAGE: $0 {start|stop|restart|status}"
    RETVAL=1
esac
exit $RETVAL


