---
galaxy_info:
  author: Baran Balkan
  description: DINGROD: iRODS monitoring point for pingdom
  company: CyVerse 
  # Some suggested licenses:
  # - BSD (default)
  # - MIT
  # - GPLv2
  # - GPLv3
  # - Apache
  # - CC-BY
  license: license (GPLv2, CC-BY, etc)
  min_ansible_version: 1.2
  platforms:
  - name: EL
    - 6
  categories:
  - monitoring
  - system
  - web
dependencies:
  - CyVerse-Ansible.irods-icommands 
